/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef my_thrift_file_CONSTANTS_H
#define my_thrift_file_CONSTANTS_H

#include "my_thrift_file_types.h"

namespace Test {

class my_thrift_fileConstants {
 public:
  my_thrift_fileConstants();

};

extern const my_thrift_fileConstants g_my_thrift_file_constants;

} // namespace

#endif
