/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "my_thrift_file_constants.h"

namespace Test {

const my_thrift_fileConstants g_my_thrift_file_constants;

my_thrift_fileConstants::my_thrift_fileConstants() {
}

} // namespace

