/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proxyserver_constants.h"

namespace Test {

const proxyserverConstants g_proxyserver_constants;

proxyserverConstants::proxyserverConstants() {
}

} // namespace

