/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proxyserver_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace Test {


Response::~Response() throw() {
}


void Response::__set_doc(const std::string& val) {
  this->doc = val;
}

void Response::__set_response_code(const int32_t val) {
  this->response_code = val;
}

uint32_t Response::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->doc);
          this->__isset.doc = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->response_code);
          this->__isset.response_code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Response::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Response");

  xfer += oprot->writeFieldBegin("doc", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->doc);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("response_code", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->response_code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Response &a, Response &b) {
  using ::std::swap;
  swap(a.doc, b.doc);
  swap(a.response_code, b.response_code);
  swap(a.__isset, b.__isset);
}

Response::Response(const Response& other0) {
  doc = other0.doc;
  response_code = other0.response_code;
  __isset = other0.__isset;
}
Response& Response::operator=(const Response& other1) {
  doc = other1.doc;
  response_code = other1.response_code;
  __isset = other1.__isset;
  return *this;
}
void Response::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Response(";
  out << "doc=" << to_string(doc);
  out << ", " << "response_code=" << to_string(response_code);
  out << ")";
}

} // namespace
