/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Proxyserver_H
#define Proxyserver_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "proxyserver_types.h"

namespace Test {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ProxyserverIf {
 public:
  virtual ~ProxyserverIf() {}
  virtual void request(Response& _return, const std::string& url) = 0;
  virtual void shutdown() = 0;
};

class ProxyserverIfFactory {
 public:
  typedef ProxyserverIf Handler;

  virtual ~ProxyserverIfFactory() {}

  virtual ProxyserverIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProxyserverIf* /* handler */) = 0;
};

class ProxyserverIfSingletonFactory : virtual public ProxyserverIfFactory {
 public:
  ProxyserverIfSingletonFactory(const boost::shared_ptr<ProxyserverIf>& iface) : iface_(iface) {}
  virtual ~ProxyserverIfSingletonFactory() {}

  virtual ProxyserverIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProxyserverIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProxyserverIf> iface_;
};

class ProxyserverNull : virtual public ProxyserverIf {
 public:
  virtual ~ProxyserverNull() {}
  void request(Response& /* _return */, const std::string& /* url */) {
    return;
  }
  void shutdown() {
    return;
  }
};

typedef struct _Proxyserver_request_args__isset {
  _Proxyserver_request_args__isset() : url(false) {}
  bool url :1;
} _Proxyserver_request_args__isset;

class Proxyserver_request_args {
 public:

  Proxyserver_request_args(const Proxyserver_request_args&);
  Proxyserver_request_args& operator=(const Proxyserver_request_args&);
  Proxyserver_request_args() : url() {
  }

  virtual ~Proxyserver_request_args() throw();
  std::string url;

  _Proxyserver_request_args__isset __isset;

  void __set_url(const std::string& val);

  bool operator == (const Proxyserver_request_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const Proxyserver_request_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxyserver_request_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Proxyserver_request_pargs {
 public:


  virtual ~Proxyserver_request_pargs() throw();
  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Proxyserver_request_result__isset {
  _Proxyserver_request_result__isset() : success(false) {}
  bool success :1;
} _Proxyserver_request_result__isset;

class Proxyserver_request_result {
 public:

  Proxyserver_request_result(const Proxyserver_request_result&);
  Proxyserver_request_result& operator=(const Proxyserver_request_result&);
  Proxyserver_request_result() {
  }

  virtual ~Proxyserver_request_result() throw();
  Response success;

  _Proxyserver_request_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const Proxyserver_request_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Proxyserver_request_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxyserver_request_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Proxyserver_request_presult__isset {
  _Proxyserver_request_presult__isset() : success(false) {}
  bool success :1;
} _Proxyserver_request_presult__isset;

class Proxyserver_request_presult {
 public:


  virtual ~Proxyserver_request_presult() throw();
  Response* success;

  _Proxyserver_request_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Proxyserver_shutdown_args {
 public:

  Proxyserver_shutdown_args(const Proxyserver_shutdown_args&);
  Proxyserver_shutdown_args& operator=(const Proxyserver_shutdown_args&);
  Proxyserver_shutdown_args() {
  }

  virtual ~Proxyserver_shutdown_args() throw();

  bool operator == (const Proxyserver_shutdown_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Proxyserver_shutdown_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxyserver_shutdown_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Proxyserver_shutdown_pargs {
 public:


  virtual ~Proxyserver_shutdown_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ProxyserverClient : virtual public ProxyserverIf {
 public:
  ProxyserverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyserverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void request(Response& _return, const std::string& url);
  void send_request(const std::string& url);
  void recv_request(Response& _return);
  void shutdown();
  void send_shutdown();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProxyserverProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProxyserverIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProxyserverProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_request(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_shutdown(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProxyserverProcessor(boost::shared_ptr<ProxyserverIf> iface) :
    iface_(iface) {
    processMap_["request"] = &ProxyserverProcessor::process_request;
    processMap_["shutdown"] = &ProxyserverProcessor::process_shutdown;
  }

  virtual ~ProxyserverProcessor() {}
};

class ProxyserverProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProxyserverProcessorFactory(const ::boost::shared_ptr< ProxyserverIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProxyserverIfFactory > handlerFactory_;
};

class ProxyserverMultiface : virtual public ProxyserverIf {
 public:
  ProxyserverMultiface(std::vector<boost::shared_ptr<ProxyserverIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProxyserverMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProxyserverIf> > ifaces_;
  ProxyserverMultiface() {}
  void add(boost::shared_ptr<ProxyserverIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void request(Response& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->request(_return, url);
    }
    ifaces_[i]->request(_return, url);
    return;
  }

  void shutdown() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shutdown();
    }
    ifaces_[i]->shutdown();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ProxyserverConcurrentClient : virtual public ProxyserverIf {
 public:
  ProxyserverConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyserverConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void request(Response& _return, const std::string& url);
  int32_t send_request(const std::string& url);
  void recv_request(Response& _return, const int32_t seqid);
  void shutdown();
  void send_shutdown();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
