/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proxyserver_TYPES_H
#define proxyserver_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace Test {

class Response;

typedef struct _Response__isset {
  _Response__isset() : doc(false), response_code(false) {}
  bool doc :1;
  bool response_code :1;
} _Response__isset;

class Response {
 public:

  Response(const Response&);
  Response& operator=(const Response&);
  Response() : doc(), response_code(0) {
  }

  virtual ~Response() throw();
  std::string doc;
  int32_t response_code;

  _Response__isset __isset;

  void __set_doc(const std::string& val);

  void __set_response_code(const int32_t val);

  bool operator == (const Response & rhs) const
  {
    if (!(doc == rhs.doc))
      return false;
    if (!(response_code == rhs.response_code))
      return false;
    return true;
  }
  bool operator != (const Response &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Response & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Response &a, Response &b);

inline std::ostream& operator<<(std::ostream& out, const Response& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
